openapi: 3.0.1
info:
  title: PlannerTableApi
  description: API Definition of PlannerAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/PlannerTable
- url: https://localhost:8253/PlannerTable
paths:
  /:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
        required: false
      responses:
        default:
          description: Default response
